apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-sm
  namespace: default
  labels:
    release: prometheus-operator  # метка, которую селектит Prometheus
spec:
  selector:
    matchLabels:
      app: scaletestapp
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s